apiVersion: tekton.dev/v1beta1
kind: CustomRun
metadata:
  generateName: celrun-get-type-
spec:
  customRef:
    apiVersion: cel.tekton.dev/v1alpha1
    kind: CEL
  params:
    - name: expression
      value: "type(1)"
