apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: simpletask
spec:
  params:
    - name: word
      type: string
    - name: suffix
      type: string
  steps:
    - name: echo
      image: ubuntu
      script: |
        #!/usr/bin/env bash
        echo "$(params.word)$(params.suffix)"
---
apiVersion: custom.tekton.dev/v1alpha1
kind: TaskLoop
metadata:
  name: simpletaskloop
spec:
  # Task to run (inline taskSpec also works)
  taskRef:
    name: simpletask
  # Parameter that contains the values to iterate
  iterateParam: word
  # Timeout (defaults to global default timeout, usually 1h00m; use "0" for no timeout)
  timeout: 60s
  # Retries for task failure
  retries: 2
---
apiVersion: tekton.dev/v1alpha1
kind: Run
metadata:
  name: simpletasklooprun
spec:
  params:
    - name: word
      value:
        - jump
        - land
        - roll
    - name: suffix
      value: ing
  ref:
    apiVersion: custom.tekton.dev/v1alpha1
    kind: TaskLoop
    name: simpletaskloop
